name: Windows Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows support
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows exe
        run: flutter build windows

      - name: Verify build output
        run: |
          $releaseFolder = "build/windows/x64/runner/Release"
          if (-Not (Test-Path $releaseFolder)) {
            Write-Error "Release folder not found at $releaseFolder"
            exit 1
          }

      - name: Zip build folder
        run: |
          $source = "build/windows/x64/runner/Release"
          $destination = "windows_build.zip"
          Compress-Archive -Path "$source\*" -DestinationPath $destination

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: windows_build.zip
